# Generated by Django 4.0.3 on 2022-10-10 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Disciplina')),
                ('horario', models.CharField(choices=[('AM', 'Mañana'), ('PM', 'Tarde'), ('AM/PM', 'AM/PM')], max_length=13, verbose_name='Horario de clases')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno matriculado',
                'verbose_name_plural': 'Alumnos matriculados',
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30, verbose_name='Nombre del plan')),
                ('precio', models.PositiveIntegerField(default=0, verbose_name='Precio del  plan')),
                ('cantidadClases', models.PositiveSmallIntegerField(default=1, verbose_name='Clases por Semana')),
                ('TipoDisciplina', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.disciplina', verbose_name='Asociado')),
            ],
            options={
                'verbose_name': 'Planes',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='UsersMetadata',
            fields=[
                ('ced_identidad', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Cedula de identidad')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N.N', 'Prefiero no Decirlo')], default='Prefiero no Decirlo', max_length=30)),
                ('vigencia', models.BooleanField(default=True, verbose_name='Vigente')),
                ('imagenPerfil', models.ImageField(blank=True, default='default.png', null=True, upload_to='Foto_Perfil', verbose_name='Imagen de Perfil')),
                ('plan', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.planes', verbose_name='Plan Inscrito')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclasses.disciplina', verbose_name='Disciplina inscrita')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User metadata',
                'verbose_name_plural': 'User metadata',
            },
        ),
    ]
