# Generated by Django 4.0.3 on 2022-10-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='imagenPerfil',
            field=models.ImageField(default='default.png', upload_to='Foto_Perfil', verbose_name='Imagen de Perfil'),
        ),
    ]
