# Generated by Django 4.0.3 on 2022-10-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_estado',
            name='cupo_disponible',
            field=models.PositiveIntegerField(null=True, verbose_name='Cupos Total'),
        ),
        migrations.AlterField(
            model_name='reserva_estado',
            name='cupo',
            field=models.PositiveIntegerField(verbose_name='Cupos Total'),
        ),
    ]
