# Generated by Django 3.2.13 on 2022-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_box_clases_matricula_perfil_planes_reserva_estado_usersmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_estado',
            name='user_creador',
            field=models.CharField(max_length=40, null=True, verbose_name='creado'),
        ),
    ]
