# Generated by Django 4.0.3 on 2022-10-10 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_alter_usersmetadata_imagenperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmetadata',
            name='imagenPerfil',
        ),
    ]
