# Generated by Django 4.0.3 on 2022-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
        migrations.AddField(
            model_name='box',
            name='user_creador',
            field=models.CharField(max_length=40, null=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
