# Generated by Django 4.0.3 on 2022-10-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_planes_alter_estudiante_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='cantidadClases',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='horario',
            field=models.CharField(choices=[('AM', 'Mañana'), ('PM', 'Tarde'), ('TODO EL DIA', 'Todo el día')], max_length=13),
        ),
    ]
