# Generated by Django 4.0.3 on 2022-11-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='comunidad',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.box', verbose_name='Comunidad'),
        ),
    ]
