# Generated by Django 4.0.3 on 2022-10-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='DisciplinaInscrita',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipoDisciplina',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
