# Generated by Django 4.0.3 on 2022-11-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0002_box_clases_matricula_perfil_planes_reserva_activa_reserva_estado_usersmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_estado',
            name='Fecha',
            field=models.DateField(null=True, verbose_name='fecha que se encuentra disponible la clase'),
        ),
        migrations.AlterField(
            model_name='reserva_activa',
            name='fecha',
            field=models.DateTimeField(verbose_name='fecha'),
        ),
    ]
