# Generated by Django 4.0.3 on 2022-10-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0003_reserva_estado_cupo_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barra_cupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.PositiveIntegerField(verbose_name='barra progreso')),
            ],
        ),
    ]
