# Generated by Django 4.0.3 on 2022-11-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0003_resersa_activa_delete_reversa_activa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resersa_activa',
            new_name='Reserva_activa',
        ),
    ]
