# Generated by Django 4.0.3 on 2022-10-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0003_remove_box_user_box_user_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='gym',
        ),
        migrations.AddField(
            model_name='box',
            name='logo',
            field=models.ImageField(default='logo/sinfoto.png', upload_to='logo', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='clases',
            name='user_creador',
            field=models.CharField(max_length=40, null=True, verbose_name='creado'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='user_creador',
            field=models.CharField(max_length=40, null=True, verbose_name='creado'),
        ),
        migrations.AddField(
            model_name='planes',
            name='user_creador',
            field=models.CharField(max_length=40, null=True, verbose_name='creado'),
        ),
    ]
