# Generated by Django 4.0.3 on 2022-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0003_alter_box_options_remove_perfil_disciplinainscrita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clases',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='clases',
            old_name='TerminoClase',
            new_name='terminoClase',
        ),
        migrations.AlterField(
            model_name='clases',
            name='modalidad',
            field=models.CharField(max_length=30, null=True, verbose_name='Modalidad de clase'),
        ),
    ]
