# Generated by Django 4.0.3 on 2022-10-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0003_rename_disinscrita_matricula_disinscrita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Gimnasio', 'verbose_name_plural': 'Gimnasios'},
        ),
        migrations.AlterModelOptions(
            name='clases',
            options={'verbose_name': 'Clases', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RenameField(
            model_name='box',
            old_name='Ubicacion',
            new_name='ubicacion',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='disInscrita',
            field=models.CharField(max_length=200, null=True, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='matricula',
            field=models.CharField(max_length=200, null=True, verbose_name='Alumno Matriculado'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='plan',
            field=models.CharField(max_length=200, null=True, verbose_name='Disciplina'),
        ),
    ]
