# Generated by Django 4.0.3 on 2022-10-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0004_remove_clases_gym_remove_planes_gym_box_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='descripcion',
            field=models.CharField(max_length=400, null=True, verbose_name='Reseña'),
        ),
    ]
