# Generated by Django 3.2.13 on 2022-10-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0004_alter_box_options_alter_clases_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='gym',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclasses.box', verbose_name='Gimnasio'),
        ),
        migrations.AddField(
            model_name='planes',
            name='gym',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.box', verbose_name='Gimnasio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='gym',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclasses.box', verbose_name='Gimnasio'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='vigencia',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagenPerfil',
            field=models.ImageField(default='perfil/sinfoto.png', upload_to='perfil', verbose_name='Imagen de Perfil'),
        ),
    ]
