# Generated by Django 4.0.3 on 2022-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0004_alter_planes_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='vigencia',
            field=models.BooleanField(default=True),
        ),
    ]
