# Generated by Django 4.0.3 on 2022-10-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0005_barra_cupo_idclase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barra_cupo',
        ),
        migrations.AddField(
            model_name='reserva_estado',
            name='barra_cupo',
            field=models.PositiveIntegerField(null=True, verbose_name='Cupos Total'),
        ),
    ]
