# Generated by Django 4.0.3 on 2022-10-11 05:07

from django.db import migrations, models
import django.db.models.deletion
import myclasses.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0005_perfil_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfiles', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='usersmetadata',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersmetadata',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='usersmetadata',
            name='vigencia',
        ),
        migrations.AddField(
            model_name='perfil',
            name='DisciplinaInscrita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.disciplina', verbose_name='Disciplina inscrita'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='plan',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.planes', verbose_name='Plan Inscrito'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vigencia',
            field=models.BooleanField(default=True, verbose_name='Vigente'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default=myclasses.models.UsersMetadata.nombreCompleto, max_length=200, null=True),
        ),
    ]
