# Generated by Django 3.2.13 on 2022-10-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0006_box_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='userID',
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myclasses.usersmetadata'),
        ),
    ]
