# Generated by Django 4.0.3 on 2022-10-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0006_alter_perfil_options_remove_usersmetadata_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.usersmetadata', verbose_name='Nombre'),
        ),
    ]
