# Generated by Django 4.0.3 on 2022-10-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0006_delete_barra_cupo_reserva_estado_barra_cupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva_estado',
            old_name='cupo_disponible',
            new_name='cupo_reservado',
        ),
    ]
