# Generated by Django 4.0.3 on 2022-10-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0006_remove_estudiante_cantidad_clases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='Titulo',
            field=models.CharField(max_length=30, verbose_name='Nombre del plan'),
        ),
    ]
