# Generated by Django 4.0.3 on 2022-10-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0007_alter_planes_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='incripciones',
            options={'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name': 'Planes', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='planes',
            name='TipoDisciplina',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.disciplina', verbose_name='Asociado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='imagenPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='Foto_Perfil', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='precio',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio del  plan'),
        ),
    ]
