# Generated by Django 4.0.3 on 2022-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0008_alter_disciplina_options_alter_incripciones_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='horario',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='vigencia',
            field=models.BooleanField(default=True, verbose_name='Vigente'),
        ),
    ]
