# Generated by Django 4.0.3 on 2022-10-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0009_remove_planes_horario_alter_estudiante_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombres',
        ),
    ]
