# Generated by Django 4.0.3 on 2022-10-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclasses', '0010_remove_estudiante_apellidomaterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsersMetadata',
            fields=[
                ('ced_identidad', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Cedula de identidad')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N.N', 'Prefiero no Decirlo')], default='Prefiero no Decirlo', max_length=30)),
                ('vigencia', models.BooleanField(default=True, verbose_name='Vigente')),
                ('imagenPerfil', models.ImageField(blank=True, null=True, upload_to='Foto_Perfil', verbose_name='Imagen de Perfil')),
                ('plan', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='myclasses.planes', verbose_name='Plan Inscrito')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclasses.disciplina', verbose_name='Disciplina inscrita')),
            ],
        ),
        migrations.AlterField(
            model_name='incripciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclasses.usersmetadata'),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
