# Generated by Django 4.0.3 on 2022-10-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclasses', '0011_planes_user_usersmetadata_alter_incripciones_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='user',
        ),
        migrations.AddField(
            model_name='usersmetadata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
