# Generated by Django 4.0.3 on 2022-10-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0012_remove_planes_user_usersmetadata_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmetadata',
            options={'verbose_name': 'User metadata', 'verbose_name_plural': 'User metadata'},
        ),
    ]
