# Generated by Django 4.0.3 on 2022-10-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0013_alter_usersmetadata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incripciones',
            options={},
        ),
        migrations.RemoveField(
            model_name='incripciones',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='incripciones',
            name='fechaIncripcion',
        ),
        migrations.AddField(
            model_name='incripciones',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incripciones',
            name='matricula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incripciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
