# Generated by Django 4.0.3 on 2022-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0014_alter_incripciones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incripciones',
            options={'verbose_name': 'Alumno matriculado', 'verbose_name_plural': 'Alumnos matriculados'},
        ),
        migrations.AlterField(
            model_name='incripciones',
            name='matricula',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='imagenPerfil',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to='Foto_Perfil', verbose_name='Imagen de Perfil'),
        ),
    ]
